### ISSUE TITLE
Stuck on Copy Mode

### ISSUE THREAD

**Issue by rodog2a1** [tofuSCHNITZEL/pi_video_looper#8]
Hi, I'm new to Raspberry Pi so the answer to my question may not be so obvious to me. I installed the video looper, but when I plug in the USB it copies over the file to the rpi. How do I configure it to just play off of the USB?

**Comment by magnip** [comment]
Hey you need to alter the video_looper.ini file. Find it on the boot partition. Instructions on what to do is in the file it self at the top with many other options for you to play with. Just open and edit with normal text editor.

**Comment by tofuSCHNITZEL** [comment]
HI @rodog2a1,
sorry in my fork the original tutorial is not linked, you can find it here:
https://learn.adafruit.com/raspberry-pi-video-looper/installation
