### ISSUE TITLE
hello_video???

### ISSUE THREAD

**Issue by Gary202** [tofuSCHNITZEL/pi_video_looper#9]
I want to loop several files seamless?? going to try hello video but dont know what files format it supports I know Raw H.264 im looking for a program that will convert my .mp4 file to raw h.264. any recommendations???? Please

**Comment by tofuSCHNITZEL** [comment]
maybe have a look at the official documentation and help....
https://learn.adafruit.com/raspberry-pi-video-looper/hello-video

**Comment by Gary202** [comment]
i have seen that but looking for a windows program? Sorry forgot to mention

**Comment by tofuSCHNITZEL** [comment]
have you tried searching for ffmpeg for windows?
(https://ffmpeg.zeranoe.com/builds/)
